version: '2'

services:
  eureka:
    build: ./discovery-server
    ports:
      - "8787:8787"

  config-server:
      build: ./ConfigServer
      ports:
        - "8888:8888"
      links:
        - eureka
      restart: always

  media-player:
      build: ./media-player
      ports:
        - "8484:8484"
      links:
        - eureka
        - config-server
      depends_on:
        - mongodb
      restart: always

  movie-info:
      build: ./movie-info
      ports:
        - "8989:8787"
      links:
        - eureka
        - config-server
      restart: always

  mongodb:
      image: mongo:latest
      container_name: "mongodb"
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/log
        - MONGODB_USER="admin"
        - MONGODB_PASS="aristo1"
      volumes:
        - ./data/db:/data/db
      ports:
          - 27017:27017
#      command: mongod --smallfiles --logpath=/dev/log # --quiet

networks:
    spring-cloud-network:
        driver: bridge