version: '2'
services:
  eureka:
    build: ./discovery-server
    volumes:
      - ./discovery-server:/app
    ports:
      - "8787:8787"

  config-server:
      build: ./ConfigServer
      volumes:
        - ./ConfigServer:/app
      ports:
        - "8888:8888"
      links:
        - eureka
      restart: always

  media-player:
      build: ./media-player
      volumes:
        - ./media-player:/app
      ports:
        - "8484:8484"
      links:
        - eureka
        - config-server
      restart: always

  movie-info:
      build: ./movie-info
      volumes:
        - ./movie-info:/app
      ports:
        - "8787:8787"
      links:
        - eureka
        - config-server
      restart: always