spring:
  application:
    name: config-server
  profile:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gilb77/webplayer
          search-paths:
            - "WebPlayerConfigProperties/{application}/{profile}"
server:
  port: 9393

